import pyodbc

# Connect to the MS SQL database
conn = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};'
                      'SERVER=your_server_name;'
                      'DATABASE=your_database_name;'
                      'UID=your_username;'
                      'PWD=your_password')

cursor = conn.cursor()

# Drop tables if they exist to start fresh (optional)
tables = ['PAYMENT', 'RENTAL', 'STAFF', 'CUSTOMER', 'INVENTORY', 'FILM_CATEGORY', 'FILM_ACTOR', 'ACTOR', 'FILM', 'CATEGORY', 'LANGUAGE', 'STORE', 'ADDRESS', 'CITY', 'COUNTRY']
for table in tables:
    cursor.execute(f"IF OBJECT_ID('{table}', 'U') IS NOT NULL DROP TABLE {table}")

# Create COUNTRY table
cursor.execute("""
CREATE TABLE COUNTRY (
    COUNTRY_ID INT PRIMARY KEY IDENTITY(1,1),
    COUNTRY NVARCHAR(50),
    LAST_UPDATE DATETIME
)
""")

# Create CITY table
cursor.execute("""
CREATE TABLE CITY (
    CITY_ID INT PRIMARY KEY IDENTITY(1,1),
    CITY NVARCHAR(50),
    COUNTRY_ID INT FOREIGN KEY REFERENCES COUNTRY(COUNTRY_ID),
    LAST_UPDATE DATETIME
)
""")

# Create ADDRESS table
cursor.execute("""
CREATE TABLE ADDRESS (
    ADDRESS_ID INT PRIMARY KEY IDENTITY(1,1),
    ADDRESS NVARCHAR(100),
    ADDRESS2 NVARCHAR(100),
    DISTRICT NVARCHAR(50),
    CITY_ID INT FOREIGN KEY REFERENCES CITY(CITY_ID),
    POSTAL_CODE NVARCHAR(20),
    PHONE NVARCHAR(20),
    LAST_UPDATE DATETIME
)
""")

# Create STORE table
cursor.execute("""
CREATE TABLE STORE (
    STORE_ID INT PRIMARY KEY IDENTITY(1,1),
    ADDRESS_ID INT FOREIGN KEY REFERENCES ADDRESS(ADDRESS_ID),
    LAST_UPDATE DATETIME
)
""")

# Create LANGUAGE table
cursor.execute("""
CREATE TABLE LANGUAGE (
    LANGUAGE_ID INT PRIMARY KEY IDENTITY(1,1),
    NAME NVARCHAR(50),
    LAST_UPDATE DATETIME
)
""")

# Create CATEGORY table
cursor.execute("""
CREATE TABLE CATEGORY (
    CATEGORY_ID INT PRIMARY KEY IDENTITY(1,1),
    NAME NVARCHAR(50),
    LAST_UPDATE DATETIME
)
""")

# Create FILM table
cursor.execute("""
CREATE TABLE FILM (
    FILM_ID INT PRIMARY KEY IDENTITY(1,1),
    TITLE NVARCHAR(255),
    DESCRIPTION NVARCHAR(MAX),
    RELEASE_YEAR INT,
    LANGUAGE_ID INT FOREIGN KEY REFERENCES LANGUAGE(LANGUAGE_ID),
    ORIGINAL_LANGUAGE_ID INT,
    RENTAL_DURATION INT,
    RENTAL_RATE DECIMAL(4,2),
    LENGTH INT,
    REPLACEMENT_COST DECIMAL(5,2),
    RATING NVARCHAR(10),
    SPECIAL_FEATURES NVARCHAR(100),
    LAST_UPDATE DATETIME
)
""")

# Create ACTOR table
cursor.execute("""
CREATE TABLE ACTOR (
    ACTOR_ID INT PRIMARY KEY IDENTITY(1,1),
    FIRST_NAME NVARCHAR(50),
    LAST_NAME NVARCHAR(50),
    LAST_UPDATE DATETIME
)
""")

# Create FILM_ACTOR table
cursor.execute("""
CREATE TABLE FILM_ACTOR (
    FILM_ID INT FOREIGN KEY REFERENCES FILM(FILM_ID),
    ACTOR_ID INT FOREIGN KEY REFERENCES ACTOR(ACTOR_ID),
    LAST_UPDATE DATETIME,
    PRIMARY KEY (FILM_ID, ACTOR_ID)
)
""")

# Create FILM_CATEGORY table
cursor.execute("""
CREATE TABLE FILM_CATEGORY (
    FILM_ID INT FOREIGN KEY REFERENCES FILM(FILM_ID),
    CATEGORY_ID INT FOREIGN KEY REFERENCES CATEGORY(CATEGORY_ID),
    LAST_UPDATE DATETIME,
    PRIMARY KEY (FILM_ID, CATEGORY_ID)
)
""")

# Create INVENTORY table
cursor.execute("""
CREATE TABLE INVENTORY (
    INVENTORY_ID INT PRIMARY KEY IDENTITY(1,1),
    FILM_ID INT FOREIGN KEY REFERENCES FILM(FILM_ID),
    STORE_ID INT FOREIGN KEY REFERENCES STORE(STORE_ID),
    LAST_UPDATE DATETIME
)
""")

# Create CUSTOMER table
cursor.execute("""
CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT PRIMARY KEY IDENTITY(1,1),
    STORE_ID INT FOREIGN KEY REFERENCES STORE(STORE_ID),
    FIRST_NAME NVARCHAR(50),
    LAST_NAME NVARCHAR(50),
    EMAIL NVARCHAR(50),
    ADDRESS_ID INT FOREIGN KEY REFERENCES ADDRESS(ADDRESS_ID),
    ACTIVE BIT,
    CREATE_DATE DATETIME,
    LAST_UPDATE DATETIME
)
""")

# Create STAFF table
cursor.execute("""
CREATE TABLE STAFF (
    STAFF_ID INT PRIMARY KEY IDENTITY(1,1),
    FIRST_NAME NVARCHAR(50),
    LAST_NAME NVARCHAR(50),
    ADDRESS_ID INT FOREIGN KEY REFERENCES ADDRESS(ADDRESS_ID),
    EMAIL NVARCHAR(50),
    STORE_ID INT FOREIGN KEY REFERENCES STORE(STORE_ID),
    ACTIVE BIT,
    USERNAME NVARCHAR(50),
    PASSWORD NVARCHAR(50),
    LAST_UPDATE DATETIME
)
""")

# Create RENTAL table
cursor.execute("""
CREATE TABLE RENTAL (
    RENTAL_ID INT PRIMARY KEY IDENTITY(1,1),
    RENTAL_DATE DATETIME,
    INVENTORY_ID INT FOREIGN KEY REFERENCES INVENTORY(INVENTORY_ID),
    CUSTOMER_ID INT FOREIGN KEY REFERENCES CUSTOMER(CUSTOMER_ID),
    RETURN_DATE DATETIME,
    STAFF_ID INT FOREIGN KEY REFERENCES STAFF(STAFF_ID),
    LAST_UPDATE DATETIME
)
""")

# Create PAYMENT table
cursor.execute("""
CREATE TABLE PAYMENT (
    PAYMENT_ID INT PRIMARY KEY IDENTITY(1,1),
    CUSTOMER_ID INT FOREIGN KEY REFERENCES CUSTOMER(CUSTOMER_ID),
    STAFF_ID INT FOREIGN KEY REFERENCES STAFF(STAFF_ID),
    RENTAL_ID INT FOREIGN KEY REFERENCES RENTAL(RENTAL_ID),
    AMOUNT DECIMAL(5,2),
    PAYMENT_DATE DATETIME,
    LAST_UPDATE DATETIME
)
""")

# Commit the transaction
conn.commit()

# Close the database connection
conn.close()